theme: jekyll-theme-minimal
title: Michael Lui
author: Michael Lui
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Zen Hang Lui Portfolio CV
show_excerpts: false # 
